[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spectrum = {path = "../spectrum"}
rusqlite = { version = "0.28.0", features = ["bundled"] }
rpassword = "7.1.0"